apiVersion: v1
kind: Service
metadata:
  name: serf-seed-service
spec:
  selector:
    app: serf-seed-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7946
      targetPort: ghossip-port
      name: ghossip-service-port
    - protocol: TCP
      port: 7373
      targetPort: rpc-port
      name: rpc-service-port
